NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 475 -- Set this to your earliest starting year
NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 400  -- the chance to get a progress to this level will increase after this date and decrease before it
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 1500
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_ENABLED = 0

Diplomacy.DEMESNE_MAX_SIZE_COUNT_MULT = 2.0 			-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_DUKE_MULT = 2.0			-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_KING_MULT = 4.0			-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_EMPEROR_MULT = 8.0			-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_STEWARDSHIP_MULT = 0.80	-- Extra Max Demesne Size from ruler and spouse stewardship
NDefines.NDiplomacy.VASSAL_LIMIT_DUKE_MULT = 5.0 				-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_KING_MULT = 10.0 				-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_EMPEROR_MULT = 20.0 			-- Extra Vassal Limit from the ruler's rank
NDefines.NDiplomacy.VASSAL_LIMIT_GREAT_DUKE_BONUS = 2.0 		-- Extra Vassal Limit for Dukes with more than one Duchy
NDefines.NDiplomacy.VASSAL_LIMIT_DIPLOMACY_MULT = 0.3			-- Extra Vasal Limit from ruler and spouse diplomacy	
NDefines.NDiplomacy.VASSAL_LIMIT_DECADENCE_MULTIPLIER = 0.50	-- Negative modifier multiplied with the current decadence.
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_DUKE_MULT = 5.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_KING_MULT = 10.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_EMPEROR_MULT = 20.0
NDefines.NDiplomacy.CONCLAVE_VASSAL_LIMIT_GREAT_DUKE_BONUS = 2.0