NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 475 -- Set this to your earliest starting year
NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 400  -- the chance to get a progress to this level will increase after this date and decrease before it
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 1500
NDefines.NDiplomacy.DEMAND_RELIGIOUS_CONVERSION_INTERACTION_ENABLED = 0
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_COUNT_MULT = 2.0 			-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_DUKE_MULT = 5.0			-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_KING_MULT = 10.0			-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_EMPEROR_MULT = 20.0			-- Extra Max Demesne Size from the ruler's rank
NDefines.NDiplomacy.DEMESNE_MAX_SIZE_STEWARDSHIP_MULT = 0.50	-- Extra Max Demesne Size from ruler and spouse stewardship